Ru.GameSchool.Web/Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using Ru.GameSchool.DataLayer.Repository;
using Ru.GameSchool.Web.Classes;
using Ru.GameSchool.Web.Classes.Helper;

namespace Ru.GameSchool.Web.Controllers
{
    public class MaterialController : BaseController
    {

        // GET: /Material/
        [Authorize(Roles = "Student, Teacher")]
        [HttpGet]
        public ActionResult Index(int? id)
        {
            if (id.HasValue)
            {
                int courseIdValue = id.Value;
                IEnumerable<LevelMaterial> materials = CourseService.GetCourseMaterials(courseIdValue).OrderByDescending(m => m.CreateDateTime); ;
                ViewBag.Materials = materials;
                ViewBag.CourseName = CourseService.GetCourse(courseIdValue).Name;
                ViewBag.Courseid = CourseService.GetCourse(courseIdValue).CourseId;

                ViewBag.Title = "Listi yfir kennsluefni";
                return View(materials);
            }

            return RedirectToAction("NotFound", "Home");
        }

        public ActionResult Index(int? id, int? contentTypeId)
        {
            if (id.HasValue && contentTypeId.HasValue)
            {
                int courseIdValue = id.Value;
                int contentTypeIdValue = contentTypeId.Value;
                IEnumerable<LevelMaterial> materials = CourseService.GetCourseMaterials(courseIdValue, contentTypeIdValue).OrderByDescending(m => m.CreateDateTime); ;
                ViewBag.Materials = materials;
                ViewBag.CourseName = CourseService.GetCourse(courseIdValue).Name;
                ViewBag.Courseid = CourseService.GetCourse(courseIdValue).CourseId;
                ViewBag.Title = "Listi yfir kennsluefni - " + CourseService.GetContentTypeNameById(contentTypeIdValue);
                return View(materials);
            }

            return RedirectToAction("NotFound", "Home");
        }


        [HttpGet]
        [Authorize(Roles = "Student, Teacher")]
        public ActionResult Get(int? id)
        {
            if (id.HasValue)
            {
                var material = LevelService.GetLevelMaterial(id.Value);
                var filepath = Settings.ProjectMaterialVirtualFolder + material.ContentId.ToString();
        
                if (material.ContentType.ContentTypeId == 1)
                {
                    ViewBag.File = filepath;
                    ViewBag.CourseName = material.Level.Course.Name;
                    ViewBag.Courseid = material.Level.Course.CourseId;
                    ViewBag.Title = material.ContentType.Name;
                    ViewBag.Name = material.Title;
                    ViewBag.Description = material.Description;
                    ViewBag.LevelMaterialId = material.LevelMaterialId;
                    return View(material);
                }
                else
                {
                    return new DownloadResult { VirtualPath = filepath, FileDownloadName = material.Filename };
                }


            }
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Student, Teacher")]
        public ActionResult Download(int? id)
        {
            if (id.HasValue)
            {
                var material = LevelService.GetLevelMaterial(id.Value);
                var filepath = Settings.ProjectMaterialVirtualFolder + material.ContentId.ToString();
             
                return new DownloadResult {VirtualPath = filepath, FileDownloadName = material.Filename};
            }
            return RedirectToAction("NotFound", "Home");
        }

        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public ActionResult Create(int? id)
        {

            ViewBag.LevelCount = GetLevelCounts(id.Value);
            ViewBag.ContentTypes = LevelService.GetContentTypes();
            ViewBag.CourseId = id.Value;
            ViewBag.CourseName = CourseService.GetCourse(id.Value).Name;
            ViewBag.Courseid = CourseService.GetCourse(id.Value).CourseId;
            ViewBag.Title = "Búa til kennsluefni";

            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult Create(LevelMaterial levelMaterial, int? id)
        {

            if (ModelState.IsValid)
            {
                if (levelMaterial.File.FirstOrDefault() != null)
                {
                    foreach (var file in levelMaterial.File)
                    {
                        Guid contentId = Guid.NewGuid();
                        if (file.ContentLength > 0)
                        {
                            var path = Path.Combine(Server.MapPath("~/Upload"), contentId.ToString());
                            ViewBag.ContentId = contentId;
                            file.SaveAs(path);
                            levelMaterial.ContentId = contentId;
                            levelMaterial.Filename = file.FileName;
                        }
                    }
                }
                
                levelMaterial.CreateDateTime = DateTime.Now;
                LevelService.CreateLevelMaterial(levelMaterial, id.Value);


                return RedirectToAction("Get", new { id = levelMaterial.LevelMaterialId });

            }
            ViewBag.LevelCount = GetLevelCounts(id.Value);
            ViewBag.ContentTypes = LevelService.GetContentTypes();
            ViewBag.CourseId = id.Value;

            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id)
        {


            if (id.HasValue)
            {
                var material = LevelService.GetLevelMaterial(id.Value);
                var courseId = material.Level.CourseId;
                ViewBag.LevelCount = GetLevelCounts(courseId);
                ViewBag.ContentTypes = LevelService.GetContentTypes();
                ViewBag.CourseName = CourseService.GetCourse(courseId).Name;
                ViewBag.Courseid = CourseService.GetCourse(courseId).CourseId;
                ViewBag.Title = "Breyta kennsluefni";

                return View(material);
            }
            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(LevelMaterial levelMaterial, int? id)
        {
            if (ModelState.IsValid)
            {
                var material = LevelService.GetLevelMaterial(levelMaterial.LevelMaterialId);
                var courseId = material.Level.CourseId;
                if (TryUpdateModel(material))
                {
                    if (material.File != null)
                    {
                        foreach (var file in material.File)
                        {
                            Guid contentId = Guid.NewGuid();
                            if (file != null && file.ContentLength > 0)
                            {
                                var path = Path.Combine(Server.MapPath("~/Upload"), contentId.ToString());
                                    //TODO: Add function to check for file extensions
                                ViewBag.ContentId = contentId;
                                file.SaveAs(path);
                                material.ContentId = contentId;
                                material.Filename = file.FileName;
                            }
                        }
                    }

                    ViewBag.CourseName = CourseService.GetCourse(courseId).Name;
                    ViewBag.Courseid = CourseService.GetCourse(courseId).CourseId;
                    ViewBag.Title = "Breyta kennsluefni";
                    ViewBag.LevelCount = GetLevelCounts(courseId);
                    ViewBag.ContentTypes = LevelService.GetContentTypes();
                    ViewBag.SuccessMessage = "Kennslugagn hefur verið uppfært";

                    LevelService.UpdateLevelMaterial(material);
                    return View(levelMaterial);
                }

            }
            else
            {
                ViewBag.ErrorMessage = "Gat ekki uppfært kennslugagn! Lagfærðu villur og reyndur aftur.";
                if (id.HasValue)
                {
                    return View(LevelService.GetLevelMaterial(id.Value));
                }   
            }
            ViewBag.LevelCount = GetLevelCounts(levelMaterial.Level.CourseId);
            ViewBag.LevelMaterialId = levelMaterial.LevelMaterialId;
            ViewBag.ContentTypes = LevelService.GetContentTypes();
            return View();
        }

        public IEnumerable<SelectListItem> GetLevelCounts(int courseId)
        {
            for (int j = 0; j <= LevelService.GetLevels(courseId).Count(); j++)
            {
                var elementAtOrDefault = LevelService.GetLevels(courseId).ElementAtOrDefault(j);
                if (elementAtOrDefault != null)
                    yield return new SelectListItem
                    {
                        Text = (elementAtOrDefault.Name == null ? "None" : elementAtOrDefault.Name),
                        Value = (elementAtOrDefault.LevelId.ToString() == "" ? "0" : elementAtOrDefault.LevelId.ToString())
                    };
            }
        }
    }
}

Ru.GameSchool.Web/Views/Material/Create.cshtml

@using (Html.BeginForm("Create", "Material", new {id=ViewBag.CourseId}, FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" } ))

{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Kennslugagn</legend>
        @Html.Partial("_MaterialForm")

        <div class="form-actions">
            <button type="submit" class="btn btn-primary" >Bæta við kennslugagni</button>
        </div>
    </fieldset>
}

Ru.GameSchool.Web/Views/Material/Edit.cshtml
@model Ru.GameSchool.DataLayer.Repository.LevelMaterial

@if (!string.IsNullOrWhiteSpace(ViewBag.SuccessMessage))
{
    <div class="alert alert-success">
        <button class="close" data-dismiss="alert">
            ×</button>
        <strong>Tókst!</strong> @ViewBag.SuccessMessage
    </div>
}
@if (!string.IsNullOrWhiteSpace(ViewBag.ErrorMessage))
{
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert">
            ×</button>
        <strong>Villa!</strong> @ViewBag.ErrorMessage
    </div>
}


@using (Html.BeginForm("Edit", "Material", new {id=Model.LevelMaterialId}, FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Kennslugagn</legend>
        @Html.HiddenFor(m => m.LevelMaterialId)
        @Html.Partial("_MaterialForm")

        <div class="form-actions">
            <button type="submit" class="btn btn-primary" >
                Uppfæra kennslugagn
            </button>
        </div>
    </fieldset>
}
<div class="control-group">
    <h3>Aðgerðir</h3>
    <div class="controls">
        <a name="button" class="btn btn-small" href="@Url.Action("Download", new { id = Model.LevelMaterialId })" >
            <i class="icon-download-alt"></i> Sækja 
        </a>
        @if (Model.ContentTypeId == 1)
        {
            <a name="button" class="btn btn-small" href="@Url.Action("Get", new {id = Model.LevelMaterialId})" >
                <i class="icon-play"></i> Spila 
            </a>
        }
    </div>
</div>

Ru.GameSchool.Web/Views/Material/Get.cshtml
<div class="well">
    <div id="gameSchoolVideo">
        <div class="videoWrapper">
            <video class="video-js vjs-default-skin" controls width="700" height="394" poster="" preload="auto" data-setup="{}">
                <source type="video/mp4" src="@ViewBag.File">
            </video>
        </div>
    </div>
    <h2>@ViewBag.Name</h2>
    <p>@ViewBag.Description</p>
    <div class="control-group">
        <div class="controls">
            <a name="button" class="btn btn-small" href="@Url.Action("Download", new { id = Model.LevelMaterialId })" >
                <i class="icon-download-alt"></i> Sækja 
            </a>
            @if (User.IsInRole("Teacher"))
            {
                <a name="button" class="btn btn-small btn-success" href="@Url.Action("Edit", new {id = Model.LevelMaterialId})" >
                    <i class="icon-edit icon-white"></i> Breyta kennslugagni
                </a>
            }
        </div>
    </div>
</div>

@*Comment hluti *@
<div class="row-fluid">
    <ul class="span6 well commentList" id="commentList">
        <div id="jsonWrapper"></div>

        <li class="commentAdd">
            <textarea id="CommentText" name="CommentText" rows="3" cols="20"></textarea>
            <div class="control-group">
                <div class="controls">
                    <button id="saveBtn" class="btn btn-info">
                        <i class="icon-comment icon-white"></i> Senda inn athugasemd
                    </button>
                </div>
            </div>
            @Html.ValidationMessage( "CommentText" )
        </li>
    </ul>
</div>

    <script id="comments" type="text/html">

    			<li>
				<a href="#"><img src='@Url.Content("~/Images/User.png")' alt="Notandi" /></a>
				<div class="commentBody">
					<a href="#">${Fullname}</a>
					<span>${Comment1}</span>
					<div>
						<abbr title='${CreateDateTime}'>${$item.formDate(CreateDateTime)}</abbr>
						<a jid="sendLike" cid="${CommentId}"><i class="icon-thumbs-up"></i> Líkar þetta</a>  
                        <span id="l_${CommentId}">
                        {{if CommentLikes.length > 0}}<img src='@Url.Content("~/Images/blank.gif")' title="{{each CommentLikes}}${Fullname} ,{{/each}} líkar þetta" alt="Líkar þetta" class="like_icon" />{{/if}}
                        
                        {{each CommentLikes}}
                        {{if $index <= 2}}${Fullname} ,{{/if}}
                        {{/each}}
                        
                        {{if CommentLikes.length > 3}} og ${CommentLikes.length - 3} öðrum{{/if}}
                        {{if CommentLikes.length > 0}}líkar þetta.{{/if}}`
                        </span>
                        
					</div>
				</div>
			</li>

</script>

<script type="text/javascript" language="javascript" >
    $(document).ready(function () {

 
        displayComments('/Json/GetComments/@ViewBag.LevelMaterialId', 'comments', 'jsonWrapper');

        $("#saveBtn").click(function () {

            var date = new Date();
            var currdate = date.getDate();

            var comment = {"Comment1": $("#CommentText").val() };

            var jqxhr = $.post("/Json/CreateComment/@ViewBag.LevelMaterialId", comment, function (data) {
                $("#CommentText").val('');
                displayComments('/Json/GetComments/@ViewBag.LevelMaterialId', 'comments', 'jsonWrapper');
            }).error(function () { alert("Sendingin misfórst. Var kannski enginn texti í athugasemdinni?"); })

        });

        

    });

    function displayComments(url, template, target) {
        var target_div = "#results";
        var template_id = "#jsonTemplate"
        if (target) { target_div = "#" + target; }
        if (template) { template_id = "#" + template; }

        AjaxProgressImg(target_div);

        $.ajax({
            type: "GET",
            contentType: "application/json; charset=utf-8",
            data: "{}",
            dataType: "json",
            url: url,
            cache: false,
            success: function (data) {

                $(target_div).empty();
                $(template_id).tmpl(data,
                {
                    formDate: function (jdate) {
                        var date = new Date(parseInt(jdate.substr(6)));
                        return date.getDate() + '.' + getIceMonth(date.getMonth()) + ' ' + date.getHours() + ':' + date.getMinutes();
                    }
                }
            ).appendTo(target_div);

                $("a[jid='sendLike']").click(function () {
                    sendLike($(this).attr("cid"));
                });

            }
        });


    }


    function sendLike(cid) {

    //alert(cid)
        var like = {
            "comment_id": cid
        };

        $.post("/JSon/LikeComment/" + cid, like, function (data) {

            displayLikes('/JSon/getLikes/' + cid, 'l_' + cid);
        }).error(function () { alert("Sendingin misfórst. Annaðhvort hefur þú nú þegar sagt að þér líki þetta eða að  athugasemdin sem þú líkaðir finnst ekki. Henni gæti hafa verið eytt."); });

    }


    function displayLikes(url, target) {
        var target_div = "#results";
        if (target) { target_div = "#" + target; }
        var ctr = 0;

        AjaxProgressImg(target_div);

        var markup = '{{if $item.count() <= 15 }} ${Fullname},{{/if}}';
        var markup2 = '${user_name} ,';
        $.template("likeTemplate", markup);
        $.template("likeTitleTemplate", markup2);
        var rand = Math.floor(Math.random() * 10000);
        var temprand = "temp" + rand;
        var likeimgrand = "likeimg" + rand;



        $.ajax({
            global: false,
            type: "GET",
            contentType: "application/json; charset=utf-8",
            data: "{}",
            dataType: "json",
            url: url,
            cache: false,
            success: function (data) {
                var likeCount = data.length;

                $(target_div).empty();
                $('<img src="/Images/blank.gif" alt="Líkar þetta" class="like_icon" id="' + likeimgrand + '"/>').appendTo(target_div);
                $('<span style="display:none" id="' + temprand + '"><span>').appendTo(target_div);


                $.tmpl("likeTitleTemplate", data).appendTo("#" + temprand);
                $("#" + likeimgrand).attr('title', $("#" + temprand).text() + ' líkar þetta');
                $("#" + temprand).remove();


                $.tmpl("likeTemplate", data, { count: function () { return ++ctr; } }).appendTo(target_div);
                if (likeCount > 3) { $(target_div).append('og ' + (likeCount - 3) + ' öðrum'); }
                $(target_div).append(' líkar þetta');


            }
        });


    }

    function AjaxProgressImg(target_div) {

        $(target_div).append('<div class="ajaxindicator_div"><img src="/images/load.gif" ></div>');

    }

    function getIceMonth(monthid) {
        var month = new Array(12)
        month[0] = "jan";
        month[1] = "feb";
        month[2] = "mar";
        month[3] = "apr";
        month[4] = "maí";
        month[5] = "jún";
        month[6] = "júl";
        month[7] = "águ";
        month[8] = "sep";
        month[9] = "okt";
        month[10] = "nóv";
        month[11] = "des";
        return month[monthid]
    }
    

</script>

Ru.GameSchool.Web/Views/Material/_MaterialForm.cshtml
@model Ru.GameSchool.DataLayer.Repository.LevelMaterial

        <div class="control-group">
            @Html.LabelFor(m => m.Title, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(m => m.Title, new { @class="input-xlarge", rel="popover" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Title)</span>
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(m => m.LevelId, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(m => m.LevelId, new SelectList(ViewBag.LevelCount, "Value", "Text"))
                <span class="help-inline">@Html.ValidationMessageFor(m => m.LevelId)</span>
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(m => m.ContentTypeId, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(m => m.ContentTypeId, new SelectList(ViewBag.ContentTypes, "ContentTypeId", "Name"))
                <span class="help-inline">@Html.ValidationMessageFor(m => m.ContentTypeId)</span>
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(m => m.File, new { @class = "control-label" })
            <div class="controls">
                <input type="file" name="File"/>
                <span class="help-inline"></span>
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(m => m.Description, new { @class = "control-label", @for="textarea" })
            <div class="controls">
                @Html.EditorFor(m => m.Description, new { @class="input-xlarge", rel="popover", rows="3" })
            </div>
        </div>