Ru.GameSchool.Web/Controllers/LevelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ru.GameSchool.DataLayer.Repository;
using Ru.GameSchool.Web.Classes.Helper;

namespace Ru.GameSchool.Web.Controllers
{
    public class LevelController : BaseController
    {
        //
        // GET: /Level/

        [Authorize(Roles = "Student,Teacher")]
        public ActionResult Get(int? id)
        {
            if (id.HasValue)
            {
                var user = MembershipHelper.GetUser();

                int levelId = id.Value;

                var model = LevelService.GetLevel(levelId);
                if (model != null)
                {

                    int userId = ViewBag.User.UserInfoId;
                    int courseId = model.CourseId;

                    ViewBag.Title = "Borð";
                    ViewBag.CourseId = courseId;
                    ViewBag.CourseName = model.Course.Name;
                    //ViewBag.Levels = LevelService.GetLevels(courseId);
                    ViewBag.LevelTabs = LevelService.GetLevelTabsByCourseIdAndUserInfoId(courseId, userId);
                    ViewBag.Projects = LevelService.GetLevelProjectsByLevelId(levelId).OrderByDescending(m => m.Start);
                    ViewBag.MaterialsVideo = LevelService.GetLevelMaterials(levelId,1).OrderByDescending(m=>m.CreateDateTime);
                    ViewBag.MaterialsSlides = LevelService.GetLevelMaterials(levelId, 2).OrderByDescending(m => m.CreateDateTime);
                    ViewBag.Announcements = AnnouncementService.GetAnnouncementsByLevelId(levelId).OrderByDescending(m => m.DisplayDateTime);
                    ViewBag.MaterialsDocs = LevelService.GetLevelMaterials(levelId, 3).OrderByDescending(m => m.CreateDateTime);
                    ViewBag.Exams = LevelService.GetLevelExamsByLevelId(levelId, userId).OrderByDescending(m => m.Start);

                    return View(model);
                }
                
            }

            return RedirectToAction("NotFound","Home");
        }


        [Authorize(Roles = "Teacher")]
        public ActionResult Create(int? id)
        //public ActionResult Create(int CoureId)
        {
            if (id.HasValue)
            {
                ViewBag.Title = "Búa til  borð";
                ViewBag.CourseId = id.Value;
                ViewBag.CourseName = CourseService.GetCourse(id.Value).Name;
                ViewBag.CourseList = new SelectList(CourseService.GetCourses(), "CourseId", "Name");

                Level model = new Level();

                model.CourseId = id.Value;
                model.Start = DateTime.Now;
                model.Stop = DateTime.Now.AddMonths(3);

                return View(model);
            }
            return RedirectToAction("NotFound", "Home");
        }


        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult Create(Level level, int? id)
        {
            if (ModelState.IsValid)
            {

                level.CreateDateTime = DateTime.Now;

                LevelService.CreateLevel(level);
                return RedirectToAction("Edit", new { Id = level.LevelId });
                
            }

            ViewBag.Title = "Búa til  borð";
            ViewBag.CourseId = id.Value;
            ViewBag.CourseName = CourseService.GetCourse(id.Value).Name;
            ViewBag.CourseList = new SelectList(CourseService.GetCourses(), "CourseId", "Name");
            level.CourseId = id.Value;

            return View(level);
            
        }



        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {

                var model = LevelService.GetLevel(id.Value);

                ViewBag.Title = "Breyta borði";
                ViewBag.CourseId = model.CourseId;
                ViewBag.CourseName = model.Course.Name;

                return View(model);
            }


            return View();
        }


        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult Edit(Level model, int? id)
        {
            var level = LevelService.GetLevel(model.LevelId);

            if (ModelState.IsValid)
            {

                if (TryUpdateModel(level))
                {
                    LevelService.UpdateLevel(level);
                }
            }

            ViewBag.Title = "Breyta borði";
            ViewBag.CourseId = model.CourseId;
            ViewBag.CourseName = level.Course.Name;

            return View(model);
        }
        /*
        public ActionResult Statistics(int id)
        {
            return View();
        }*/

        [Authorize(Roles = "Student, Teacher")]
        public ActionResult Announcements(int? id)
        {
            if (id.HasValue)
            {
                ViewBag.Course = CourseService.GetCourse(id.Value);
                ViewBag.CourseId = id.Value; 
                var announcements = AnnouncementService.GetAnnouncementsByLevelId(id.Value);
                ViewBag.Announcements = announcements;
            }

            return View();
        }

        [Authorize(Roles = "Teacher")]
        public ActionResult CreateAnnouncement(int? id)
        {
            var model = new Announcement();
            if (id.HasValue)
            {
                var user = MembershipHelper.GetUser();
                ViewBag.CourseId = id.Value;
                model.CourseId = id.Value;
                model.DisplayDateTime = DateTime.Now;
                ViewBag.CourseList = new SelectList(CourseService.GetCoursesByUserInfoId(user.UserInfoId), "CourseId", "Name");
                ViewBag.LevelList = new SelectList(LevelService.GetLevels(id.Value), "LevelId", "Name");
            }

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult CreateAnnouncement(Announcement model, int? id)
        {
            var user = MembershipHelper.GetUser();
            
            if (ModelState.IsValid)
            {
                AnnouncementService.CreateAnnouncement(model, user.UserInfoId);

                return RedirectToAction("Announcement", "Course", new {id = model.AnnouncementId});
            }

            if (id.HasValue)
            {
                ViewBag.CourseId = id.Value;
                ViewBag.CourseList = new SelectList(CourseService.GetCoursesByUserInfoId(user.UserInfoId), "CourseId", "Name");
                ViewBag.LevelList = new SelectList(LevelService.GetLevels(id.Value), "LevelId", "Name");
            }

            return View(model);
        }

        [Authorize(Roles = "Teacher")]
        public ActionResult EditAnnouncement(int? id)
        {
            if (id.HasValue)
            {
                var model = AnnouncementService.GetAnnouncementByAnnouncementId(id.Value);

                var user = MembershipHelper.GetUser();
                ViewBag.CourseId = model.CourseId;
                ViewBag.CourseList = new SelectList(CourseService.GetCoursesByUserInfoId(user.UserInfoId), "CourseId", "Name");
                ViewBag.LevelList = new SelectList(LevelService.GetLevels(model.CourseId), "LevelId", "Name");

                return View(model);
            }

            return RedirectToAction("Notfound", "Home");
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public ActionResult EditAnnouncement(Announcement model, int? id)
        {
            if (id.HasValue)
            {
                var user = MembershipHelper.GetUser();
                if (ModelState.IsValid)
                {
                    var announcement = AnnouncementService.GetAnnouncementByAnnouncementId(id.Value);

                    if (TryUpdateModel(announcement))
                    {
                        AnnouncementService.UpdateAnnouncement(announcement, user.UserInfoId);
                        return RedirectToAction("Announcement", "Course", new { id = announcement.AnnouncementId });
                    }
                }

                ViewBag.CourseId = model.CourseId;
                ViewBag.CourseList = new SelectList(CourseService.GetCoursesByUserInfoId(user.UserInfoId), "CourseId",
                                                    "Name");
                ViewBag.LevelList = new SelectList(LevelService.GetLevels(model.CourseId), "LevelId", "Name");
                return View(model);
            }

            return RedirectToAction("Notfound", "Home");
        }
    }
}

Ru.GameSchool.Web/Views/Project/Create.cshtml
@using Ru.GameSchool.DataLayer.Repository
@model LevelProject
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>
@using (Html.BeginForm("Create", "Project", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Upplýsingar um verkefni</legend>
        <div class="control-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Name, new { @class = "input-xlarge", rel = "popover" })
                <span class="help-inline">@Html.ValidationMessageFor(model => model.Name)</span>
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(m => m.LevelId, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(m => m.LevelId, new SelectList(ViewBag.LevelCount, "Value", "Text"))
                <span class="help-inline">@Html.ValidationMessageFor(m => m.LevelId)</span>
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.GradePercentageValue, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(m => m.GradePercentageValue, new SelectList(ViewBag.GradePercentageValue, "Value", "Text"))
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.Start, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(model => model.Start, new { @data_datepicker = "datepicker", rel = "popover", id = "start" })
                <span class="date" style="visibility: hidden;">Byrjunardagsetning má ekki vera stærri
                    en endadagsetning</span> <span class="help-inline">@Html.ValidationMessageFor(model => model.Start)</span>
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.Stop, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(model => model.Stop, new { @data_datepicker = "datepicker", rel = "popover", id = "stop" })
                <span class="date" style="visibility: hidden; color: yellow;">*</span> <span class="help-inline">@Html.ValidationMessageFor(model => model.Stop)</span>
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Description, new { @class = "input-xlarge", rel = "popover", cols = "30", rows = "10" })
                <span class="help-inline">@Html.ValidationMessageFor(model => model.Description)</span>
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.File, new { @class = "control-label" })
            <div class="controls">
                <input type="file" name="File"/>
            </div>
        </div>
        

        <div class="form-actions">
            <button type="submit" id="submit" class="btn btn-primary">Bæta við verkefni</button>
            @Html.ActionLink("Aftur á forsíðu verkefna", "Index", new { id = ViewBag.CourseId }, new { @class = "btn btn-small" })
        </div>
    </fieldset>
}

<script type="text/javascript">
    $(function () {
        jQuery.validator.methods["date"] = function (value, element) {
            return true;
        };

        $.datepicker.setDefaults({ validateDate: 'false' });
        $.datepicker.regional['is-IS']
        $('.Start').datepicker({ dateFormat: "d.m.yy 00:00:01" });
        $('.Stop').datepicker({ dateFormat: "d.m.yy 23:59:59" });


        var start = $("#start");
        var stop = $("#stop");
        var submit = $("#submit");
        var error = $(".date");

        submit.click(function () {
            if (start.val() > stop.val()) {
                error.css('visibility', 'visible');
                return false;
            }
        });
    });

</script>

Ru.GameSchool.Web/Views/Project/Delete.cshtml
@using Ru.GameSchool.DataLayer.Repository
@model LevelProject
@{
    ViewBag.Title = "Eyða verkefni";
}
        @if (!string.IsNullOrWhiteSpace(ViewBag.ErrorMessage))
        {
            <div class="alert alert-error">
                <button class="close" data-dismiss="alert">
                    ×</button>
                <strong>Villa!</strong> @ViewBag.ErrorMessage
            </div>
        }
<br />
<h2>
    Ertu viss um að þú viljir eyða verkefni?</h2>
<fieldset>
    <div class="control-group">
        @Html.LabelFor(model => model.Name, new { @class = "control-label" })
        <div class="controls">
            <strong>@Html.DisplayTextFor(model => model.Name)</strong>
        </div>
    </div>
    <div class="control-group">
        @Html.LabelFor(model => model.Description, new { @class = "control-label" })
        <div class="controls">
            <strong>@Html.DisplayTextFor(model => model.Description)</strong>
        </div>
    </div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-success">
                    Eyða verkefni</button>
            </div>
        </div>
        @Html.ActionLink("Aftur á forsíðu verkefna", "Index", new { id = ViewBag.CourseId }, new { @class = "btn btn-small" })
    </p>
}

Ru.GameSchool.Web/Views/Project/Edit.cshtml
@using Ru.GameSchool.DataLayer.Repository
@model LevelProject
@using (Html.BeginForm("Edit", "Project", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Upplýsingar um verkefni</legend>
        @Html.HiddenFor(model => model.LevelProjectId)
        @if (!string.IsNullOrWhiteSpace(ViewBag.SuccessMessage))
        {
            <div class="alert alert-success">
                <button class="close" data-dismiss="alert">
                    ×</button>
                <strong>Tókst!</strong> @ViewBag.SuccessMessage
            </div>
        }
        @if (!string.IsNullOrWhiteSpace(ViewBag.ErrorMessage))
        {
            <div class="alert alert-error">
                <button class="close" data-dismiss="alert">
                    ×</button>
                <strong>Villa!</strong> @ViewBag.ErrorMessage
            </div>
        }
        <div class="control-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Name, new { @class = "input-xlarge", rel = "popover" })
                <span class="help-inline">@Html.ValidationMessageFor(model => model.Name)</span>
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.LevelId, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownList("LevelId", string.Empty)
                <span class="help-inline">@Html.ValidationMessageFor(model => model.LevelId)</span>
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.GradePercentageValue, new { @class = "control-label" })
            <div class="controls">
                @Html.DropDownListFor(m => m.GradePercentageValue, new SelectList(ViewBag.GradePercentageValue, "Value", "Text"))
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.Start, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(model => model.Start, new { @data_datepicker = "datepicker", rel = "popover",id = "start" }) <span class="date" style="visibility: hidden;">Byrjunardagsetning má ekki vera stærri en endadagsetning</span>
                <span class="help-inline">@Html.ValidationMessageFor(model => model.Start)</span>
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.Stop, new { @class = "control-label" })
            <div class="controls">
                @Html.TextBoxFor(model => model.Stop, new { @data_datepicker = "datepicker", rel = "popover",id ="stop" }) <span class="date" style="visibility: hidden; color:yellow;">*</span>
                <span class="help-inline">@Html.ValidationMessageFor(model => model.Stop)</span>
            </div>
        </div>
        <div class="control-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.Description, new { @class = "input-xlarge", rel = "popover", cols = "30", rows = "10" })
                <span class="help-inline">@Html.ValidationMessageFor(model => model.Description)</span>
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.File, new { @class = "control-label" })
            <div class="controls">
                <input type="file" name="File"/>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <button type="submit" id="submit" class="btn btn-primary">Breyta verkefni</button>
                @Html.ActionLink("Aftur á forsíðu verkefna", "Index", new { id = ViewBag.CourseId }, new { @class = "btn btn-small"})
            </div>
        </div>
    </fieldset>
}

<script>
    $(document).ready(function () {

        jQuery.validator.methods["date"] = function (value, element) {
            return true;
        };

        $.datepicker.setDefaults({ validateDate: 'false' });
        $.datepicker.regional['is-IS']
        $('.Start').datepicker({ dateFormat: "d.m.yy 00:00:01" });
        $('.Stop').datepicker({ dateFormat: "d.m.yy 23:59:59" });


        var start = $("#start");
        var stop = $("#stop");
        var submit = $("#submit");
        var error = $(".date");

        submit.click(function () {
            if (start.val() > stop.val()) {
                error.css('visibility', 'visible');
                return false;
            }
        });

    });
</script>

Ru.GameSchool.Web/Views/Project/Get.cshtml
@using Ru.GameSchool.DataLayer.Repository
@model LevelProject
@using (Html.BeginForm("ReturnProject", "Project", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal" }))
{ 
    
    @Html.HiddenFor(m => m.LevelProjectId)
    
    <article>
    <h3><span class="gray">Skilafrestur @Html.DisplayFor(model => model.Stop) | @Html.DisplayNameFor(model => model.GradePercentageValue) - @Html.DisplayFor(model => model.GradePercentageValue)%</span></h3>
   
              <div class="control-group">
      <h3>  @Html.DisplayNameFor(model => model.Name)</h3>
    <div class="container-fluid">
        <div class="controls">
            @Html.DisplayFor(model => model.Name)
        </div>
    </div>
    </div>
   
    <div class="control-group">
        <h3>  @Html.DisplayNameFor(model => model.Level.Name)</h3>
        <div class="container-fluid">
            <div class="controls">
                @Html.DisplayFor(model => model.Level.Name)
            </div>
        </div>
    </div>


        <div class="control-group">
            <h3>  @Html.DisplayNameFor(model => model.Description)</h3>
            <div class="container-fluid">
                <div class="controls">
                    @Html.DisplayFor(model => model.Description)
                </div>
            </div>
        </div>
        
        <div class="control-group">
        <h3> Sækja skrá: @Html.DisplayFor(model => model.Filename)</h3>
        <div class="container-fluid">
            <div class="controls">
                <a name="button" class="btn btn-small" href="@Url.Action("Download", new { id = Model.LevelProjectId })" >
                <i class="icon-download-alt"></i> Sækja 
            </a>
            </div>
        </div>
    </div>

        <div class="control-group">
            @Html.LabelFor(model => model.File, new { @class = "control-label" })
            <div class="controls">
                <input type="file" name="File" />
                <span class="help-inline">@Html.ValidationMessageFor(model => model.ContentID)</span>
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.UserFeedback, new { @class = "control-label" })
            <div class="controls">
                @Html.EditorFor(model => model.UserFeedback, new { @class = "input-xlarge", rel = "popover", cols = "30", rows = "10" })
                <span class="help-inline">@Html.ValidationMessageFor(model => model.UserFeedback)</span>
            </div>
        </div>


    <div class="control-group"><p>Leyfilegar skrár:
             @foreach (var item in ViewBag.AllowedFileExtensions)
             {
               <i>  @item  </i>
             }
         </p></div>
    
</article>
    //if (innerInnerItem.LevelProjectResults.Where(u => u.UserInfoId == ViewBag.UserInfoId).Any(x => x.Grade == null))
            
             if (!(Model.Stop < DateTime.Now))
             {
                 if (Model.LevelProjectResults.Select(s => s.UserInfoId).FirstOrDefault() != ViewBag.UserInfoId &&
                     !Model.LevelProjectResults.Where(s => s.UserInfoId == ViewBag.UserInfoId).Any(x => x.Grade == null))
                 {

    <div class="control-group">
        <label class="control-label">
        </label>
        <div class="controls">
            <button type="submit" id="submitbtn" class="btn btn-success">
                Skila verkefni</button>
        </div>
    </div>   
                 }
                 else
                 {
    <text>Búið að skila verkefni</text>
                 }

             }
             else
             {
    <strong>Skilafrestur búinn!</strong>  
             }


}
<div class="control-group">
    <div class="controls">
        @Html.ActionLink("Aftur á forsíðu verkefna", "Index", new { id = ViewBag.CourseId }, new { @class = "btn btn-small" })
    </div>
</div>

Ru.GameSchool.Web/Views/Project/Index.cshtml
@using Ru.GameSchool.DataLayer.Repository
@model IEnumerable<Course>
@foreach (var course in Model)
{
    <h2>@course.Name</h2>
    <i>@course.Identifier</i>
    <table class="table table-striped table-bordered table-condensed">
        <tbody>
            <tr>
                <th>
                    Nafn verkefnis
                </th>
                <th>
                    Skilafrestur
                </th>
                <th>
                    Lýsing
                </th>
                <th>
                    Borð
                </th>
                @if (User.IsInRole("Teacher"))
                {
                    <th>
                        Fjöldi búinn að skila
                    </th>
                    <th>
                        Fjöldi óyfirfarna verkefna
                    </th>
                    <th>
                        Aðgerðir kennara
                    </th>
                }
                else
                {
                    <th>
                        Einkunn
                    </th>
                    <th>
                        Athugasemd kennara
                    </th>
                }
            </tr>
            @foreach (var innerItem in course.Levels)
            {
                foreach (var innerInnerItem in innerItem.LevelProjects.OrderByDescending(x => x.Stop))
                {
                    if (!(innerInnerItem.Start > DateTime.Now && User.IsInRole("Student"))) // Ekki sýna verkefni sem eru ekki byrjuð
                    {     
                <tr>
                    <td>
                        <!-- -->
                        @if (innerInnerItem.Start < DateTime.Now && User.IsInRole("Student"))
                        {
                            @Html.ActionLink(@innerInnerItem.Name, "Get", new { id = @innerInnerItem.LevelProjectId })if (innerInnerItem.IsReturned(ViewBag.User.UserInfoId))
                                                                                                                      {<span class="label label-success new-material">Skilað</span>}
                                                                                                                      else if (innerInnerItem.IsNew())
                                                                                                                      {<span class="label label-important new-material">Nýtt</span>}
                        }
                        else if (User.IsInRole("Teacher"))
                        {
                            @Html.ActionLink(@innerInnerItem.Name, "TeacherGet", new { id = @innerInnerItem.LevelProjectId, courseId = ViewBag.CourseId })if (@innerInnerItem.Start.AddHours(23) >= DateTime.Now)
                                                                                                                             {<span class="label label-important new-material">Nýtt</span>}
                        }
                        else if (innerInnerItem.Stop < DateTime.Now)
                        {
                            <i>Skilafrestur búinn!</i>
                        }
                    </td>
                    <td>
                        @innerInnerItem.Stop.ToShortDateString()
                    </td>
                    <td>
                        @innerInnerItem.Description
                    </td>
                    <td>
                        @Html.ActionLink(@innerInnerItem.Level.Name, "Get", "Level", new { id = innerInnerItem.LevelId }, null)
                    </td>
                    @if (User.IsInRole("Teacher"))
                    {

                        <td>
                            @innerInnerItem.LevelProjectResults.Count
                        </td>
                        <td>
                            @innerInnerItem.LevelProjectResults.Count(x => x.Grade == null)
                        </td>
                        <td>
                            <a name="button" class="btn btn-mini" href="@Url.Action("Edit", new { id = innerInnerItem.LevelProjectId, courseId = ViewBag.CourseId })" >
                                <i class="icon-edit"></i>Breyta </a> | <a name="button" class="btn btn-mini" href="@Url.Action("Delete", new { id = innerInnerItem.LevelProjectId, courseId = ViewBag.CourseId })" >
                                    <i class="icon-edit"></i>Eyða </a>
                        </td>
                    }
                    else if (User.IsInRole("Student"))
                    {
                        if(innerInnerItem.Stop < DateTime.Now)
                        {
                            <td><i>Skilafrestur búinn!</i></td>
                             <td>
                        </td>
                        }
                        else if (innerInnerItem.LevelProjectResults.Where(u => u.UserInfoId == ViewBag.UserInfoId).Any(x => x.Grade == null))
                        {
                        <td>
                            <i>Enginn einkunn kominn!</i>
                        </td>
                        <td>
                        </td>
                        }
                        else if (innerInnerItem.LevelProjectResults.Select(x => x.UserInfoId).FirstOrDefault() != ViewBag.UserInfoId)
                        {
                        <td>
                            <i>Ekki búið að skila verkefni!</i>
                        </td>
                        <td>
                        </td>
                        }
                        else
                        {
                            foreach (var result in innerInnerItem.LevelProjectResults.Where(s => s.UserInfoId == ViewBag.UserInfoId))
                            {
                        <td>
                            <i>@result.Grade</i>
                        </td>
                        <td>
                            @result.TeacherFeedback
                        </td>
                            }
                        }
                    }
                </tr>
                    }
                }
            }
        </tbody>
    </table>
            if (User.IsInRole("Teacher"))
            {
        <p>
            @Html.ActionLink("Búa til nýtt verkefni", "Create", new { id = course.CourseId }, new { @class = "btn btn-primary" })
        </p>
    }
}